Update to 0.84.0 and offer modules to reduce build size
fulcro-legacy/semantic-ui-wrapper pull request #7
Opened 2018-12-30 03:24 UTC by j1mr10rd4n

After @awkay 's comment in https://github.com/fulcrologic/semantic-ui-wrapper/pull/6#issuecomment-442948621, the generatd factories namespace composes individual modules which can be used separately to reduce build size.

In addition, the devcards examples are ported to workspaces and the figwheel build is replaced by shadow-cljs.

2018-12-30 04:36 UTC, awkay commented
Missing package.json for workspaces build.  Did you forget to check it in?

2018-12-30 04:47 UTC, awkay requested changes
Thanks for doing all that work...I have a lot of comments, and we'll have to discuss a few things...one is the fact that the change I'm proposing would break non-shadow users (if they exist).

2018-12-30 04:47 UTC, awkay commented on project.clj
> +                 [nubank/workspaces "1.0.2"]
workspaces should be a dev dependency, and shadow-cljs should not be a dependency at all.  This is a library.  Do not cause transitive dependency requirements for the consumers of it.

2018-12-30 04:47 UTC, awkay commented on shadow-cljs.edn
> +          ; :main       {:target     :browser
Why are you checking in commented source?

2018-12-30 04:47 UTC, awkay commented on project.clj
> +             ; :dev {:source-paths ["src/main" "src/cards"]
Don't check in commented out source.  Either it belongs or it doesn't. Git can track the old versions

2018-12-30 04:47 UTC, awkay commented on src/dev/user.clj
> +;FIGWHEEL
No check-ins of commented sources

2018-12-30 04:47 UTC, awkay commented on src/main/fulcrologic/semantic_ui/factories.cljs
> -(defn factory-apply
This is a library and these were public. You can deprecate them and make a new ns for them, but don't delete them. Make them refer to the new versions, just like you did for all of the factories.

2018-12-30 04:47 UTC, awkay commented on src/main/fulcrologic/semantic_ui/modules/ui_accordion.cljs
> +    ["semantic-ui-react" :refer [Accordion AccordionPanel AccordionContent AccordionTitle AccordionAccordion]]))
Did you check that this reduces the advanced compile size?  You're doing a require against the top-level index.js, which will pull in everything.

I could be wrong, but I think you've got to drop to the module level on the require to get the size reduction.

```
npx shadow-cljs run shadow.cljs.build-report build-name report.html
```

I think the proper requires use the path to the module...something like this:

```
(ns fulcrologic.semantic-ui.modules.ui-button
  (:require
    [fulcrologic.semantic-ui.factory-helpers :as h]
    ["semantic-ui-react/dist/commonjs/elements/Button/Button" :default Button]
    ["semantic-ui-react/dist/commonjs/elements/Button/ButtonOr" :default ButtonOr]
    ["semantic-ui-react/dist/commonjs/elements/Button/ButtonGroup" :default ButtonGroup]
    ["semantic-ui-react/dist/commonjs/elements/Button/ButtonContent" :default ButtonContent]))
```

Use the report to see if that helps.  It is a bit more complexity in the code generation, but the whole point was to make if obvious what could be removed from the build.  To get the ideal smallest size I'd guess there would need to be a namespace per element/module.

I could be wrong on this.  My experience, though, is that the current implementation causes *all* of them to end up in an advanced build, and I think your changes will not change that.

NOTE: This change makes the library *only* work with shadow-cljs, since there is no such require statement in standard cljs.

2018-12-30 05:00 UTC, awkay commented on src/main/fulcrologic/semantic_ui/modules/ui_accordion.cljs
> +    ["semantic-ui-react" :refer [Accordion AccordionPanel AccordionContent AccordionTitle AccordionAccordion]]))
I did check this, and it does work as I describe.  Your changes will not affect build size unless you do the above.

I got 500K on your build when just using button, and 100k with my version (again just using button).  The other bad news is that even when I did it that way it pulled in a lot of cruft I didn't directly use...I'm guessing because some of those components use things like dimmer.

2019-01-16 02:58 UTC, j1mr10rd4n commented
Superseded by work on [optimise-for-shadow-cljs branch](https://github.com/fulcrologic/semantic-ui-wrapper/tree/optimise-for-shadow-cljs).

2019-01-16 02:58 UTC, closed without merging

2019-01-16 22:24 UTC, thosmos commented on src/main/fulcrologic/semantic_ui/modules/ui_accordion.cljs
> +    ["semantic-ui-react" :refer [Accordion AccordionPanel AccordionContent AccordionTitle AccordionAccordion]]))
Would it work to generate a separate foreign-libs reference for each js file in a deps.cljs file?  This might make it available for non-shadow-js users?